### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by jenson-chang** [UBC-MDS/academic-success-prediction#24]
- [x] Missing sections in CONTRIBUTING.md: 
  - Your First Code Contribution 
  - Improving The Documentation 
  - Style guides 
  - Commit Messages
- [x] Add code to download data from source
- [x] Results - Update analysis plot/table to show specific results and not everything
- [x] Discussion - More details needed. Need to tie back to problem. 
- [x] References - References are not referred to in the report
