### ISSUE TITLE
Milestone 3 task list

### ISSUE THREAD

**Issue by MCatherine1994** [UBC-MDS/academic-success-prediction#27]
- [x] #28
     - [x] Save download file into csv raw data
     - [x] Save train set and test set
- [x] #29
     - [x] Import train csv file 
     - [x] export EDA plots
- [x] #30
     - [x] #32
     - [x] #31 
    
Quarto part:
- [x] (Catherine) convert jupyter notebook to .qmd
- [x] (Siddarth) add confusion matrix table (table need to follow the Quarto requirement) and add some discussion
- [x] (Jenson) image and table formatting and description name
- [x] (Siddarth) setup header and table of content
- [x] (Catherine) update reference citation
- [x] (Siddarth) replace hardcoded values
- [x] (Jenson) render quarto report
